name: Model repository checks

on:
  workflow_dispatch:
  pull_request:

jobs:
  ruff:
    uses: CAVISE/pipelines/.github/workflows/python-ruff.yml@main
    with:
      run-lint: true
      run-format-check: true

  type-check:
    uses: CAVISE/pipelines/.github/workflows/python-mypy.yml@main
    with:
      python-version: "3.12"
      target-path: scripts
      follow-imports-silent: true
      cache-dependency-path: |
        requirements.txt
        pyproject.toml
      requirements-file: requirements.txt

  unused-code-check:
    uses: CAVISE/pipelines/.github/workflows/python-deadcode.yml@main
    with:
      python-version: "3.12"
      target-path: scripts

  pre-commit:
    uses: CAVISE/pipelines/.github/workflows/python-pre-commit.yml@main
    with:
      python-version: "3.12"
      skip-hooks: ruff-check,ruff-format,mypy,deadcode
      all-files: true
